### ISSUE TITLE
Reload the workspace

### ISSUE THREAD

**Issue by beogivaljr** [boocs/fast-header-intellisense#2]
Every time a switch from a .h to a .cpp or vice versa, vscode says I have to reload the project (`Reload the workspace for the settings change to take effect.`) is it a known issue? Can I ignore it?

**Comment by beogivaljr** [comment]
Also the intellisense cache seems to reset on every reload.

**Comment by boocs** [comment]
Yikes, yeah I've kind of abandoned this project and don't use it. I never liked that tag parser doesn't have red squiggles so it's confusing if something is wrong with a header. 

If it also resets cache on every reload then that's even worse. It never did the reload thing when I first created it. I might just remove this project.
